#!/bin/sh
### SSHUTTLE INIT.D SERVICE SCRIPT
### REQUIRED MINIMUM Python version of 2.7

SCRIPT=/etc/sshuttle/sshuttle.py
RUNAS=sshuttle
LOGFILE=/var/log/messages

start() {
  su -c "$SCRIPT start" $RUNAS >&2
}

stop() {
  su -c "$SCRIPT stop" $RUNAS >&2
}

restart() {
    stop
    start 
}

status() {
  su -c "$SCRIPT status" >&2
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
